spring.application.name=Journal App
spring.data.mongodb.uri=mongodb+srv://aniketsuryavanshi4954:HH4T9495KqVFaFSk@cluster0.vqzayx6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
#this is for index creation ie for replication
spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

